/*
Generate random vehicle plate numbers

Assume a vehicle plate number consists of three uppercase letters followed by four digits. Write a program to generate a plate number. 

Note: Uppercase letters and digits can be randomly generated by the use of Math.random() method.

Number plate format: SDC5575
 */
public class number_plate {
    public static void main(String[] args) {
        String letters = "ABCDEFGHIJKLMNOPQRSTUVWXYZ";
        String numbers = "0123456789";
        String plate = "";
        for (int i = 0; i < 3; i++) {
            plate += letters.charAt((int) (Math.random() * 26));
        }
        for (int i = 0; i < 4; i++) {
            plate += numbers.charAt((int) (Math.random() * 10));
        }
        System.out.println(plate);
    }

    
}
